---
version: '3'

services:

  atmosphere-alt:
    image: 'alt_atmo'
    volumes:
      - 'alt_env:/opt/env/atmo:rw'
      - 'alt_sockets:/tmp:rw'
      - './logs/celery/atmo:/var/log/celery:rw'
      - './logs/atmosphere:/opt/dev/atmosphere/logs:rw'

  troposphere-alt:
    image: 'alt_tropo'
    volumes:
      - 'alt_env:/opt/env/atmo:rw'
      - 'alt_sockets:/tmp:rw'
      - 'alt_tropo:/opt/dev/troposphere:rw'
      - './logs/celery/tropo:/var/log/celery:rw'
    depends_on:
      - 'atmosphere-alt'

  nginx-alt:
    image: 'alt_nginx'
    volumes:
      - 'alt_sockets:/tmp'
      - 'alt_tropo:/opt/dev/troposphere:rw'
      - './logs/nginx:/var/log/nginx:rw'
    depends_on:
      - 'atmosphere-alt'
      - 'troposphere-alt'
    ports:
      - '443:443'
      - '80:80'

  guacamole:
    image: 'guacamole/guacamole:0.9.13-incubating'
    environment:
      GUACAMOLE_HOME: '/guac_stuff'
      GUACD_HOSTNAME: 'guacd'
    volumes:
      - './guacamole:/guac_stuff:rw'
    ports:
      - '8080:8080'

  guacd:
    image: 'guacamole/guacd:0.9.13-incubating'

volumes:
  alt_env:
    external: true
  alt_sockets:
    external: true
  alt_tropo:
    external: true
