---

- name: Wait for Postgres database to be active
  hosts: troposphere
  tasks:
    - name: Wait for Postgres database to be active
      wait_for:
        host: 'postgres'
        port: '5432'
        state: 'started'
        delay: '10'

- name: Create Troposphere database
  hosts: troposphere
  tasks:
    - name: database 'troposphere' is created
      postgresql_db:
        name: 'troposphere'
        state: 'present'
        login_user: 'atmo_app'
        login_host: 'postgres'
        login_password: 'atmosphere'
