---

- name: Wait for Postgres database to be active
  hosts: troposphere
  tasks:
    - name: Wait for Postgres database to be active
      wait_for:
        host: 'postgres'
        port: '5432'
        state: 'started'
        delay: '10'

- name: Create Troposphere database
  hosts: troposphere
  tasks:
    - name: database 'troposphere' is created
      postgresql_db:
        name: 'troposphere'
        state: 'present'
        login_user: 'atmo_app'
        login_host: 'postgres'
        login_password: 'atmosphere'

- name: Finish Troposphere database setup
  hosts: troposphere
  roles:
    - { role: app-django-manage-collectstatic,
        APP_BASE_DIR: "{{ TROPOSPHERE_LOCATION | default(troposphere_directory_path) }}",
        VIRTUAL_ENV: "{{ VIRTUAL_ENV_TROPOSPHERE | default(troposphere_virtualenv_path) }}",
        STATIC_DIR_PATH: 'troposphere/tropo-static',
        DJANGO_SETTINGS_MODULE: 'troposphere.settings',
        tags: ['troposphere', 'manage-collectstatic']}

    - { role: app-django-manage-migrate,
        APP_BASE_DIR: "{{ TROPOSPHERE_LOCATION | default(troposphere_directory_path) }}",
        VIRTUAL_ENV: "{{ VIRTUAL_ENV_TROPOSPHERE | default(troposphere_virtualenv_path) }}",
        DJANGO_SETTINGS_MODULE: 'troposphere.settings',
        tags: ['troposphere', 'migrate', 'manage-migrate'] }
