---
- name: Fix web_desktop.py for Docker
  hosts: troposphere
  tasks:
    - name: Make sure API_SERVER is set to 'nginx' by hard-coding web_desktop.py
      lineinfile:
        state: present
        path: "/opt/dev/troposphere/troposphere/views/web_desktop.py"
        regexp: '^            api_root=settings.API_V2_ROOT,$'
        line: "            api_root='https://nginx/api/v2',"
        backrefs: yes

    - name: Fix Guacamole URL with hard-coding
      lineinfile:
        state: present
        path: "/opt/dev/troposphere/troposphere/views/web_desktop.py"
        regexp: "^    url = .+$"
        line: "    url = data.get('token_url').replace('guacamole','localhost',1)"
        backrefs: yes
