---
- name: Genereate Troposphere ini configs
  hosts: troposphere
  roles:
    - { role: app-generate-ini-config,
        template_vars: "{{ TROPO }}",
        APP_BASE_DIR: "{{ TROPOSPHERE_LOCATION | default(troposphere_directory_path) }}",
        VIRTUAL_ENV: "{{ VIRTUAL_ENV_TROPOSPHERE | default(troposphere_virtualenv_path) }}",
        tags: ['troposphere', 'generate-config'] }

- name: Make sure DATABASE_HOST is set to 'postgres'
  hosts: troposphere
  tasks:
    - name: Make sure DATABASE_HOST is set to 'postgres'
      lineinfile:
        state: present
        path: '/opt/dev/troposphere/variables.ini'
        regexp: '^DATABASE_HOST = ""$'
        line: 'DATABASE_HOST = "postgres"'

    - name: Make sure ADDITIONAL_ALLOWED_HOSTNAMES has 'nginx'
      lineinfile:
        state: present
        path: "/opt/dev/troposphere/variables.ini"
        regexp: '^ADDITIONAL_ALLOWED_HOSTNAMES = \[\]'
        line: "ADDITIONAL_ALLOWED_HOSTNAMES = ['nginx']"

    - name: Make sure API_SERVER is set to 'nginx' by hard-coding web_desktop.py
      lineinfile:
        state: present
        path: "/opt/dev/troposphere/troposphere/views/web_desktop.py"
        regexp: '^            api_root=settings.API_V2_ROOT,$'
        line: "            api_root='https://nginx/api/v2',"

    - name: Fix Guacamole URL with hard-coding
      lineinfile:
        state: present
        path: "/opt/dev/troposphere/troposphere/views/web_desktop.py"
        regexp: "^    url = .+$"
        line: "    url = data.get('token_url').replace('guacamole','localhost',1)"

    - name: run generate script for app
      shell: '/opt/env/troposphere/bin/python /opt/dev/troposphere/configure'
