---
- name: Generate ini configs for atmosphere and atmosphere-ansible
  hosts: atmosphere
  roles:
    - { role: app-generate-ini-config,
        template_vars: "{{ ATMO }}",
        APP_BASE_DIR: "{{ ATMOSPHERE_LOCATION | default(atmosphere_directory_path) }}",
        VIRTUAL_ENV: "{{ VIRTUAL_ENV_ATMOSPHERE | default(atmosphere_virtualenv_path) }}",
        tags: ['atmosphere', 'generate-config'] }

    - { role: app-setup-ssh-keys,
        APP_BASE_DIR: "{{ ATMOSPHERE_LOCATION | default(atmosphere_directory_path) }}",
        SSH_PRIV_KEY: "{{ ID_RSA | default('') }}",
        SSH_PUB_KEY: "{{ ID_RSA_PUB | default('') }}",
        tags: ['atmosphere', 'ansible-deploy', 'setup-ssh-keys'] }

    - { role: app-install-instance-deploy-automation,
        APP_BASE_DIR: "{{ ATMOSPHERE_LOCATION | default(atmosphere_directory_path) }}",
        INSTANCE_DEPLOY_AUTOMATION_DIR: "{{ ANSIBLE_DEPLOY_LOCATION | default(atmosphere_ansible_directory_path) }}",
        INSTANCE_DEPLOY_AUTOMATION_HOSTS_FILE: "{{ ANSIBLE_HOSTS_FILE | default('') }}",
        INSTANCE_DEPLOY_AUTOMATION_GROUP_VARS_FOLDER: "{{ ANSIBLE_GROUP_VARS_FOLDER | default('') }}",
        tags: ['atmosphere', 'ansible-deploy'] }

    - { role: app-generate-ini-config,
        template_vars: "{{ ATMOSPHERE_ANSIBLE }}",
        APP_BASE_DIR: "{{ ANSIBLE_DEPLOY_LOCATION | default(atmosphere_ansible_directory_path) }}",
        VIRTUAL_ENV: "{{ VIRTUAL_ENV_ATMOSPHERE | default(atmosphere_ansible_virtualenv_path) }}",
        tags: ['atmosphere', 'ansible-deploy'] }

- name: Make sure DATABASE_HOST is set to 'postgres'
  hosts: atmosphere
  tasks:
    - name: Make sure DATABASE_HOST is set to 'postgres'
      shell: sed -i 's/^DATABASE_HOST = ""$/DATABASE_HOST = "postgres"/' /opt/dev/atmosphere/variables.ini

    - name: Make sure ADDITIONAL_ALLOWED_HOSTNAMES includes 'nginx'
      shell: sed -i 's/^ADDITIONAL_ALLOWED_HOSTNAMES = \[\]$/ADDITIONAL_ALLOWED_HOSTNAMES = \["nginx"\]/' /opt/dev/atmosphere/variables.ini

    - name: run generate script for app
      shell: '/opt/env/atmo/bin/python /opt/dev/atmosphere/configure'
