---

- name: Wait for Postgres database to be active
  hosts: atmosphere
  tasks:
    - name: Wait for Postgres database to be active
      wait_for:
        host: 'postgres'
        port: '5432'
        state: 'started'
        delay: '10'
